name: 打包项目
on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm-build工作
    runs-on: window

    steps:
    - name: 读取仓库内容 ~
      run: |
        npm install
        npm run build
    - name: '部署'
      uses: JamesIves/github-page-deploy-action@v4
      with: 
        branch: pev-pages
        folder: build
